### ISSUE TITLE
Uniform sampling for random init

### ISSUE THREAD

**Issue by maurapintor** [pralab/secml-torch#73]
The implementation of the uniform sampling in the $\ell_p$-ball should be implemented as an initializer.
The idea is to sample from the $\ell_p$-sphere and then sample uniformly the radius.

This should be placed in https://github.com/pralab/secml-torch/blob/main/src/secmlt/optimization/random_perturb.py

## Useful resources

**Papers / theory:**
* https://mathoverflow.net/questions/9185/how-to-generate-random-points-in-ell-p-balls
* https://baezortega.github.io/2018/10/14/hypersphere-sampling
* https://compneuro.uwaterloo.ca/files/publications/voelker.2017.pdf

**Existing implementations:**
This is an implementation in JAX: https://github.com/google/jax/issues/10876

**Comment by battistabiggio** [comment]
If needed, code from gnormal can be found here: https://github.com/google/jax/issues/10875
